version: '1.0'
name: pipeline
displayName: pipeline
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
stages:
  - name: stage-0e16e07b
    displayName: runner
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: shell@agent
        name: execute_shell
        displayName: Shell 脚本执行
        hostGroupID: NodeGroup
        script: |-
          PATH=$PATH:/opt/node/bin
          ln -s /opt/src/note-book/ .
          cd note-book/Markdown-notebook/
          git fetch --all
          git reset --hard origin/master
          git pull
          rm -rf ./_book ./book-html
          sed -i "s/title:.*$/title\: \'运维开发绿皮书-${GITEE_COMMIT}\'\,/g" book.js
          npm run build 
          pwd
          ls -la ./
          cd _book &&  pwd && ls -la ./
          rm -rf /var/www/html/*
          mv * /var/www/html/
          echo "删除旧的构建"
          bash ../../../clean_build.sh /root/gitee_go_agent/workspace/
strategy:
  blocking: false
permissions:
  - role: admin
    members: []
