version: '1.0'
name: pipeline
displayName: pipeline
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
  pr:
    branches:
      precise:
        - master
stages:
  - name: stage-0e16e07b
    displayName: build_with_shell_script
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: shell@agent
        name: customer_runner
        displayName: Shell 脚本执行
        hostGroupID: NodeGroup
        script: |-
          PATH=$PATH:/opt/node/bin
          ln -s /opt/src/note-book/ .
          cd note-book/Markdown-notebook/
          echo "==========远程仓库同步BEGIN=========="
          git fetch --all
          git reset --hard origin/master
          git pull
          echo "==========远程仓库同步END=========="
          echo "==========Github代码库同步BEGIN=========="
          git push github master:master
          echo "==========Github代码库同步END=========="
          echo "==========clean workspace start=========="
          rm -rf ./_book ./book-html
          echo "==========clean workspace end=========="
          sed -i "s/title:.*$/title\: \'运维开发绿皮书   Version: ${GITEE_SHORT_COMMIT}.\'\,/g" book.js
          gitbook build --log debug | tee ${web_home}build.txt build.txt 2>&1 > /dev/null
          cp -rvf build.txt _book/build.txt
          cd _book 
          rm -rf ${web_home}*
          mv * ${web_home}
strategy:
  blocking: false
permissions:
  - role: admin
    members: []
