version: '1.0'
name: pipeline
displayName: pipeline
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
stages:
  - name: stage-0e16e07b
    displayName: runner
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: shell@agent
        name: execute_shell
        displayName: Shell 脚本执行
        hostGroupID: NodeGroup
        script: |-
          PATH=$PATH:/opt/node/bin
          ln -s /opt/src/note-book/ .
          cd note-book/Markdown-notebook/
          git fetch --all
          git reset --hard origin/master
          git pull
          npm install gitbook-cli -g
          rm -rf ./_book ./book-html
          sed -i "s/title:.*$/title\: \'运维开发绿皮书-${GITEE_COMMIT}\'\,/g" book.js
          npm run build 
          pwd
          ls -la ./
          cp -rf  _book book-html
          cd _book &&  pwd && ls -la ./
          rm -rf /var/www/html/*
          mv * /var/www/html/
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./Markdown-notebook/book-html
  - name: stage-7a5a0838
    displayName: upload
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
  - name: stage-9b33c478
    displayName: deploy
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布
        dependArtifact: output
        version: 1.0.0.0
        autoIncrement: true
strategy:
  blocking: false
permissions:
  - role: admin
    members: []
