name: 发布无域名限制版本

on:
  push:
    branches:
      # 确保这是你正在使用的分支名称
      - main

permissions:
  contents: write

jobs:
  build-no-domain:
    runs-on: ubuntu-latest
    steps:
      - name: 拉源码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: 更改主机名
        run: |-
          sed -i 's/hostname: "https:\/\/paper-dragon.github.io",/hostname: "",/g' src/.vuepress/theme.ts
          grep hostname src/.vuepress/theme.ts

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: true
          version: 8

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: "requirements.txt"

      - name: 安装python依赖
        run: pip install -r requirements.txt

      - name: 生成图云
        run: python main.py

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run docs:build
          > src/.vuepress/dist/.nojekyll

      - name: 上传构建产物
        uses: actions/upload-artifact@v3.1.2
        with:
          name: no-domain-html
          path: src/.vuepress/dist/
          # 产物保留时间
          retention-days: 3

  publish-docker:
    runs-on: ubuntu-latest
    needs: build-no-domain
    steps:
      - name: 拉源码
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 把当前时间放到环境变量里
        run: echo "TAGDATE=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      - name: 下载上一个步骤生成的产物
        uses: actions/download-artifact@v2.1.1
        with:
          name: no-domain-html
          path: ./file

      - name: 登陆到DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建和推送docker镜像
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/notebook:${{ env.TAGDATE }}



